Fixed a bug where a single quote code lead into an parse error
mschindler83/fints-hbci-php pull request #19
Opened 2016-09-19 16:04 UTC by dsentker

I've faced a strange bug where a single quote in the payer's name could lead into missing results.

Below there is an sample raw response excerpt which containts two single quotes in line 7:
```
:20:STARTUMSE
:25:12340000/1005751234
:28C:00000/001
:60F:C160813EUR8575,66
:61:1609140814CR89,37N062NONREF
:86:166?00GUTSCHRIFT?109253?20SVWZ+FooBarBaz Example?21Foo
Bar?30GENOEDF1SN1?31DE50140912340005719216?32'Example Company Name' GmbH
:61:1609140814CR70,82N062NONREF
:86:166?00GUTSCHRIFT?108249?20EREF+Max Mustermann 
:86:166?00GUTSCHRIFT?108227?20SVWZ+Example Message?30SOLADES1R
VB?31DE16612301100111887741?32SomeOtherGuy
:62F:C160914EUR8785,85
```

After some debugging, i found out that  in Fhp\Response\Response::__construct() a simple explode is used to separate the response into segments. However, if other strings containts unexpected quotes, the rest of the response is not parsed properly.

The solution is to split the raw response more precisely: The split is done when a single quote is followed by four or more uppercase characters, a colon and a number.
The chance,  that a payers name looks like _'FOOBAR:7_ is very low.

Additionally, i added empty lines between class properties and shortened `array()` to `[]`

2016-09-20 10:00 UTC, mschindler83 commented on lib/Fhp/Response/Response.php
> +        $this->segments = preg_split("#(')(?=[A-Z]{4,}:\d|')#", $rawResponse);
I think it would make more sense to use
`#'(?=[A-Z]{4,}:\d)|'#` ?
The you would also remove the last "'" from the very last segment.

2016-09-20 10:02 UTC, mschindler83 requested changes
Please do not remove the old array syntax as it will break BC with older PHP versions.
And I've added one suggestion to your regex. Maybe it makes sense.

2016-09-20 13:09 UTC, dsentker commented
Okay, i removed the short array syntax and changed the regex (it worked with my test data as well).

2016-09-20 18:31 UTC, mschindler83 approved these changes
LGTM

2016-09-20 18:31 UTC, merged

2018-07-17 09:36 UTC, roben commented
This still fails when splitting transactions containing the string `:86:166?00GUTSCHRIFT?109227?20EREF+07-11/52'''KdNr.K13341?2183?22`

I think the regexp misses some carrets, it needs to be `/'(?=[A-Z]{4,}:(\d|'))/`

2018-07-17 09:58 UTC, roben commented
I improved the regexp and will create an issue.